plugins:
  - github
env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  camelcase: off
  github/no-then: off
  semi: off
  import/no-commonjs: off
  filenames/match-regex: off
  i18n-text/no-en: off
overrides:
  - files: ['**/*.test.js']
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
ignorePatterns:
  - dist/
  - lib/
  - node_modules/